name: hys
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_tex: ^4.0.0
  path: ^1.7.0
  cupertino_icons: ^1.0.0
  firebase_core: ^1.10.2
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.4
  firebase_storage: ^10.2.4
  cloud_firestore: 3.1.5
  provider: ^6.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  google_fonts: 2.2.0
  velocity_x: ^3.3.0
  http: ^0.13.0
  image_picker: ^0.7.0
  flutter_google_places: 0.3.0
  searchable_dropdown: ^1.1.3
  file_picker: ^4.3.0
  titled_navigation_bar: ^4.1.0
  readmore: ^2.0.0
  cached_network_image: 3.0.0
  open_file: ^3.0.3
  package_info: ^0.4.0+14
  permission_handler: ^3.0.0
  audioplayer: ^0.8.1
  record_mp3: ^2.1.0
  camera: ^0.9.4+5
  avatar_glow: ^1.2.0
  url_launcher: ^6.0.9
  flutter_placeholder_textlines: ^1.0.4
  image_crop: ^0.3.4
  flutter_custom_dialog: ^1.0.20
  expandable: ^4.1.4
  agora_rtc_engine: ^4.0.0
  firebase_messaging: ^11.2.4
  get_it: ^3.0.0+1
  flutter_keyboard_size:
  flutter_js: ^0.2.2+0
  fluttericon: ^1.0.7
  flutter_reaction_button: ^1.0.7+3
  super_tooltip: ^0.9.6
  flutter_xlider: ^3.4.0
  inview_notifier_list: ^3.0.0
  flutter_mentions: ^2.0.1
  bubble: ^1.1.9+1
  dio: ^4.0.4
  persistent_bottom_nav_bar: ^3.2.0
  awesome_dialog: ^1.3.2
  fluttermoji: ^0.2.0-nullsafety.0
  multi_image_picker: ^4.7.14
  percent_indicator: ^2.1.9+1
  chewie:
  video_player: ^2.0.0
  simple_gesture_detector: ^0.1.6
  video_compress: ^2.1.1
  photo_view: ^0.10.3
  video_thumbnail: ^0.4.3
  connectivity: ^3.0.0
  story_designer: ^1.0.0
  story_view: ^0.13.1
  scrollable_positioned_list: ^0.1.10
  audio_video_progress_bar: ^0.1.0
  sliding_up_panel: ^1.0.2
  flutter_image_compress: ^1.1.0
  smart_select: ^4.3.2
  sticky_headers: ^0.1.8
  roundcheckbox: ^1.0.0+1
  circular_check_box: ^1.0.2
  group_radio_button: ^1.0.1
  grouped_buttons: ^1.0.4
  modal_bottom_sheet: ^1.0.0+1
  sliding_sheet: ^0.4.0
  location: ^4.0.0
  google_maps_flutter: ^2.1.1
  flutter_icons: ^1.1.0
  easy_gradient_text: ^1.0.0
  flutter_gradient_colors: ^1.0.0
  flutter_ffmpeg: ^0.4.0
  flutter_countdown_timer: ^3.0.1
  flutter_scale: ^0.1.2
  numeric_keyboard: ^1.0.0
  floatingpanel: ^1.1.3
  notustohtml: ^1.0.0-rc.1
  flutter_html: ^2.0.0
  audio_service: ^0.18.3
  just_audio:
  audioplayers: ^0.20.1
  flutter_plugin_android_lifecycle: ^2.0.5
  flutter_math_fork: ^0.4.2+2
  animations: ^2.0.2
  device_info_plus: ^3.2.0
  flex_color_scheme:
  flutter_archive: ^4.1.0
  flutter_mailer: ^2.0.1
  intl: ^0.17.0
  just_waveform: ^0.0.1
  linalg: ^0.4.0
  logger: ^1.1.0
  record: ^3.0.2
  rxdart: ^0.26.0
  shared_preferences: ^2.0.11
  sprung: ^3.0.0
  elegant_notification: ^1.5.0
  html_editor_enhanced: ^2.4.0+1
  syncfusion_flutter_calendar: ^19.4.50


  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      ref: master
      path: packages/zefyr
  assets_audio_player: ^3.0.3+3
  flutter_cache_manager: ^3.3.0
  syncfusion_flutter_sliders: ^19.4.53
  flutter_local_notifications: ^9.3.3
  progress_dialog: ^1.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ncrt_class_10_cover.jpg
    - assets/reactions/
    - assets/profile/
    - assets/shortcuts/
    - assets/backgrounds/
    - assets/text.gif
    - assets/flutter_tex_banner.png
    - assets/podcast_bg.png
    - fonts/Army.ttf
    - fonts/Budhrg.ttf
    - fonts/CELTG.ttf
    - fonts/hillock.ttf
    - fonts/intimacy.ttf
    - fonts/SansationLight.ttf
    - fonts/slenmini.ttf
    - fonts/SubaccuzRegular.ttf

  fonts:
    - family: Cardo
      fonts:
        - asset: fonts/Cardo-Bold.ttf
        - asset: fonts/Cardo-Regular.ttf
        - asset: fonts/Cardo-Italic.ttf

    - family: ProductSans
      fonts:
        - asset: fonts/Product-Sans-Bold.ttf

